### ISSUE TITLE
Update Firefox addon 1.1.4->1.1.6

### ISSUE THREAD

**Issue by yo1dog** [grantwinney/hide-google-doodles#11]
Firefox add-on is still at version 1.1.4. Can you update to latest 1.1.6?

https://addons.mozilla.org/en-US/firefox/addon/hide-doodles/

**Comment by grantwinney** [comment]
I haven't used Firefox in awhile, and can't remember the login to the account I uploaded the extension to, lol. 🙄  None of my regular email accounts work, and there's no support to contact about it. So.. I don't think I can update it unless I re-upload it under a new account.

**Comment by grantwinney** [comment]
To anyone from [discourse.mozilla.org](https://discourse.mozilla.org/t/i-cant-remember-the-email-address-i-used-to-upload-my-addons-so-i-cant-access-the-account/36785), hopefully this is enough to prove my identity. 😬

**Comment by grantwinney** [comment]
Alright, go ahead and try it again. It should be updated now.

**Comment by yo1dog** [comment]
Works great! Thanks!
