### ISSUE TITLE
Google Logo is too big on google maps

### ISSUE THREAD

**Issue by mandresybilly** [grantwinney/hide-google-doodles#12]
The display logo is a little too big on google maps and it touches the search bar. Not very disturbing but for  aesthetics, it maybe worth a look. I am posting two screenshots. One when the extension is enabled and another one when it is disabled. That way, you can see the difference in the dimensions on the Logo size.
[Extension is DISABLED](https://imgur.com/0wA8N3Z)
[Extension is ENABLED](https://imgur.com/U2kbttj)

[The url of the search I made](https://www.google.com/search?q=hospital&npsic=0&rflfq=1&rlha=0&rllag=39776302,30485253,1966&tbm=lcl&ved=2ahUKEwiukofR44zhAhXKxcQBHS3RCN0QtgN6BAgBEAQ&tbs=lrf:!2m1!1e2!2m1!1e3!2m1!1e16!3sIAE,lf:1,lf_ui:2&rldoc=1#rlfi=hd:;si:;mv:!1m2!1d39.801079699999995!2d30.549240899999997!2m2!1d39.7468423!2d30.4346357;tbs:lrf:!2m1!1e2!2m1!1e3!2m1!1e16!3sIAE,lf:1,lf_ui:2)

**Comment by grantwinney** [comment]
## Extension is DISABLED
![Extension is DISABLED](https://i.imgur.com/0wA8N3Z.png)

## Extension is ENABLED
![Extension is ENABLED](https://imgur.com/U2kbttj.png)

**Comment by grantwinney** [comment]
Hopefully that does it. Might take a little while for the new version to be published. Thanks for the helpful images demonstrating the problem!
