### ISSUE TITLE
Doodle appears on Gmail right now

### ISSUE THREAD

**Issue by billyandriam** [grantwinney/hide-google-doodles#13]
I know that the primary purpose of the extension was to hide doodles on Google search. Yet, it would be a good idea to stretch its ability on all google-related services since there are doodles on Gmail now. 
![Capture](https://user-images.githubusercontent.com/33964719/55359949-bef7e980-54db-11e9-9a01-a9ce6db314a6.PNG)

**Comment by grantwinney** [comment]
Interesting... could be more work than I want to get into. Do they usually show a doodle? This one appears to just be because it's Gmail's birthday.

---

```html
<div class="gb_Rb">
    <div class="gb_Sb gb_ae">
        <a class="gb_Vd gb_Tb gb_ce" href="#inbox" title="Gmail"><img class="gb_ma" src="https://ssl.gstatic.com/ui/v1/icons/mail/rfr/logo_gmail_15_dark_1x.png" srcset="https://ssl.gstatic.com/ui/v1/icons/mail/rfr/logo_gmail_15_dark_2x.png 2x ,https://ssl.gstatic.com/ui/v1/icons/mail/rfr/logo_gmail_15_dark_1x.png 1x" style="width:109px;height:40px"></a>
    </div>
</div>
```

**Comment by billyandriam** [comment]
Exactly. It's there only because of Gmail birthday. But I wanted to bring it into your attention in case you might to anticipate on future occurrence of the doodles on Google services. 
Who knows? Maybe google will bring doodles to GoogleDrive on GoogleDrive's birthday.

**Comment by grantwinney** [comment]
I went ahead and replaced it, so if they show a doodle in Gmail again it should be hidden. I didn't replace it in any other services, just in case my change to Gmail messed something up... but it seems to be okay. May "fix" the other services later too.

**Comment by billyandriam** [comment]
Thank you very much!
So pretty much it hides the "Gmail" word, right?

**Comment by grantwinney** [comment]
No problem. It's a single image. The bday doodle was https://ssl.gstatic.com/ui/v1/icons/mail/rfr/logo_gmail_15_dark_1x.png, so I just told it to always use the default https://ssl.gstatic.com/ui/v1/icons/mail/rfr/logo_gmail_lockup_dark_1x.png.

**Comment by billyandriam** [comment]
I see. But it doesn't display the **Gmail scripture** on my inbox though.
![Capture](https://user-images.githubusercontent.com/33964719/56080580-87f2d380-5e0b-11e9-88b3-1cada7b83a4a.PNG)

**Comment by billyandriam** [comment]
This other image might be more appropriate as a substitute.
![logo_gmail_lockup_default_1x](https://user-images.githubusercontent.com/33964719/56081280-27b45f80-5e14-11e9-8b86-f81ef0117bdc.png)

**Comment by grantwinney** [comment]
That's weird.. I don't know why yours would be different. If you right-click on the image and check the page source, is it loading this? https://ssl.gstatic.com/ui/v1/icons/mail/rfr/logo_gmail_lockup_dark_1x.png

Or something else?

**Comment by billyandriam** [comment]
Yes. When I right-click on it and select "open image in a new tab", I see it clearly as you uploaded. But my gmail background is by default white so the scripture blends in. 
I wish I knew how you got your background color in blue.

**Comment by grantwinney** [comment]
That sounds too bright! Mine's not solid blue, it's part of a picture of some water and mountains.

_[Gmail themes - You can pick a theme to change your Gmail background](https://support.google.com/mail/answer/112508?hl=en)_
