### ISSUE TITLE
Would it possible to hide additional animations from the search results?

### ISSUE THREAD

**Issue by billyandriam** [grantwinney/hide-google-doodles#15]
This might be off-topic but still, I love a distraction-free experience and so far, the extension is doing a great job!
When I search for "christmas", there is this additional animated gif on the right side of the search results, so I don't know how to get it removed.
![Screenshot from 2019-12-20 22-05-05](https://user-images.githubusercontent.com/33964719/71301916-482ab580-23b6-11ea-96c7-f7db0366748b.png)

**Comment by grantwinney** [comment]
Hm, interesting. It's an element with an ID of "easter-egg", so if you install an extension like [Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us) and add a style with a bit of css like this, it should take care of it.

```
#easter-egg { display: none; }
```

I don't know how I feel about adding that to this extension. It'd be easy enough, but I imagine I could extend it to hide a _lot_ of extra stuff like this..

**Comment by billyandriam** [comment]
I get you completely. That's why I thought this might be an off-topic thing at first. I will try adding that CSS rule on Stylus. Mine was just a suggestion, like adding that as an option. Because for my part, I just need functionality and don't care about all the additional visual stuff.

**Comment by grantwinney** [comment]
Glad to hear it worked! I use Stylus for a lot of one-off stuff for other sites too.

I was thinking about your suggestion, and I suppose anyone sick enough of the doodles to install this extension wouldn't mind hiding those easter eggs either, so I added it to the extension.

**Comment by billyandriam** [comment]
Thanks a million for your dedication sir! I'm closing this issue now.
