### ISSUE TITLE
Disable doodles on https://www.google.com/finance ?

### ISSUE THREAD

**Issue by ed0109** [grantwinney/hide-google-doodles#18]
Would it be possible to disable doodles on Google Finance?  Thank you.  
![doodle](https://user-images.githubusercontent.com/60204767/72948973-c246b500-3d3b-11ea-8399-e1eca7c6d251.jpg)

**Comment by grantwinney** [comment]
Yep, easily! Still waiting on them to approve a previous fix, then I'll be able to upload the change.

**Comment by ed0109** [comment]
Great!  Thanks, Grant.

**Comment by grantwinney** [comment]
Alright, should be good to go next time there's something to block. Let me know if it doesn't.

**Comment by ed0109** [comment]
Yep, It is good!  Thanks again.
