### ISSUE TITLE
Google image problem

### ISSUE THREAD

**Issue by laurennibbs87** [grantwinney/hide-google-doodles#19]
Google image has also a google doodle. How get rid them?

**Comment by laurennibbs87** [comment]
> Google image has also a google doodle. How get rid them?

Google chrome not working for google image

**Comment by grantwinney** [comment]
The search results page used a different class name on the element than other pages do. An update is available for Firefox and Chrome, so update the extension and see if it works now. Let me know if you have any other issues.
