### ISSUE TITLE
Firefox add-ons website reports that Hide Google Doodles is not available for Firefox 60 on Linux

### ISSUE THREAD

**Issue by quanticle** [grantwinney/hide-google-doodles#2]
I'm trying to install the Hide Google Doodles extension on Firefox 60.0.1 on Ubuntu 18.04 Linux, and the Firefox add-ons site is saying, "This extension is not supported on your platform." I'm a bit confused by that, since there doesn't appear to be anything platform-specific in the extension, and the extension installed just fine on Firefox 60 on OSX.

**Comment by grantwinney** [comment]
Sorry I didn't see this earlier. Github doesn't seem to notify me of issues on my own repos unless I'm "watching" them. I'll take a look at it.

**Comment by grantwinney** [comment]
When I originally uploaded it, I enabled it for Windows and Mac only. I should've just left it on "All Platforms" which includes Linux environments. It's fixed now, so if you're interested in trying it again, it should work.

Thanks for the heads up!
