### ISSUE TITLE
Suddenly Broken

### ISSUE THREAD

**Issue by davidlkent** [grantwinney/hide-google-doodles#20]
Love this beyond words, but it's broken now on Chrome. Did they change something?

**Comment by grantwinney** [comment]
They may have.. thanks for the heads up. I'll check it out the next time I see a doodle.

**Comment by grantwinney** [comment]
I just tested this in Chrome and Brave (chromium based), and it's blocking the today's doodle in both.

Are you still having issues? Do you see any errors in the browser console, or does the page look _any_ different when the extension is enabled vs disabled?

**Comment by davidlkent** [comment]
Thanks for checking, Grant. It’s working today for me as well (and thank goodness) – interim “bad” update?

**Comment by davidlkent** [comment]
Thanks for checking, Grant. It’s working today for me as well (and thank goodness) – interim “bad” Google update?

**Comment by grantwinney** [comment]
Glad to hear it, it's hard to say. It works by hiding certain elements on the page according to their ID, so if they changed the ID's then it would break the add-on. Maybe they did for a couple days, and then rolled something back? Anyway, glad to hear it's working now. Let me know if you have problems again!

**Comment by davidlkent** [comment]
Thanks, Grant.
