### ISSUE TITLE
Does it work or not?

### ISSUE THREAD

**Issue by igenyar** [grantwinney/hide-google-doodles#21]
The doodle still appears. I am using chrome Version 84.0.4147.135 (Official Build) (64-bit).

**Comment by grantwinney** [comment]
Are you talking about the main search page (they show it in several places)? I just tried it on 85.0.4183.83 and it's working.

![image](https://user-images.githubusercontent.com/1354059/91627035-34dadb80-e982-11ea-963d-2bed0d2dd6bd.png)

**Comment by igenyar** [comment]
OK, I didn't read your info carefully. It is for new tab and I use your method of setting background, and it works. Thank you!
