### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by anfo55** [grantwinney/hide-google-doodles#3]
Hi Grant
Unless I'm doing something wrong which I can't exclude, the addon doesn't seem to be working for me?
Downloaded/installed 4 September 2018.
![2018-09-04_16-40-06](https://user-images.githubusercontent.com/19360769/45020487-b896b180-b061-11e8-8795-b64357acefcc.png)

**Comment by grantwinney** [comment]
It's possible something changed on their end, like the name of that doodle element in their html markup.

I visited google.com and a bunch of their other country-specific urls but I can't seem to get a doodle to come up today - which google search url are you using? Also, is that Chrome? _(I have it in the Firefox store too, plus Opera can install Chrome addons)._ When I see a doodle again, I'll check out what's going on.

**Comment by anfo55** [comment]
Hi Grant
I was fearful of posting this in case I was wrong, which I may still be!
To answer some of your questions:

- https://www.google.com.au/ is the Australian Google domain name I use

- Yes Firefox which is and likely to be for as long as it is in active development my choice

But I will double check when the next Doodle comes along as well

**Comment by grantwinney** [comment]
Don't worry about being wrong! :) There's really nothing to configure, other than having javascript enabled, so if it's not working it very well might be a bug. Thanks, I'll keep an eye out too.

**Comment by anfo55** [comment]
Well, here is where I may be wrong. I use Noscript, so it may be a case that I had a script blocked. However according to my screenshot above, it looks like the icon for NoScript ("S") is allowing all.
Let's see what the next Doodle does.

**Comment by grantwinney** [comment]
Do you see anything in the [dev console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console) _(Ctrl-Shift-K or Cmd-Option-K)_ when the page loads, that looks like it might be an error message? It's a long shot and there might be a lot of other stuff displayed in there too, but I'm not sure what might be causing that.

It's frustrating that when I visit google.com.au (or the honduras or romania sites that are supposed to have doodles today too) from a browser that doesn't have the extension, google doesn't show me the doodles. I don't know if maybe it's because they know I'm not in the country that has the doodle... if I can't figure it out, I'll have to wait until there's one for my area that I _can_ see...

**Comment by anfo55** [comment]
There may be errors (see link). In the meantime I am going to disable Adblock and Noscript addons and see what happens
https://pastebin.com/HPKiCu8y

**Comment by anfo55** [comment]
So, disabling all my addons except Hide Doodle doesn't change the situation. I'd just say that a dev that is passionate about fixing their work is more important than fixing the issue for little old me, so take your time if necessary, I'm in absolutely no rush and am happy I'm helping :)

**Comment by grantwinney** [comment]
No problem, and thanks for helping. :) Feel free to only help as far as you want... I am pretty curious why this is failing though. It's a pretty small extension.

I don't _think_ the hosts file would affect this, but I don't know much about it honestly. Those error messages in the console seem to be originating from _something_ trying to run against certain elements on the page _(possibly Adblocker before you disabled it?)_ using `document.getElementById()` but those elements aren't ones used on the Google search page and they aren't the ones I look for (which are just the `logocont` and `lga` IDs), so I don't think those errors have anything to do with this extension.

I checked the source code for the search page, and the IDs this extension looks for haven't changed, so it _should_ work. 😬 I'll have to think about this one. Is there any chance you have a spare machine running Firefox to try this on? If it happens on there too, then that'd be something at least. And if it doesn't, then at least we know it's this one machine. 😅 

It's also available for Chrome, so if really wanted to dig into it you could _(just temporarily!)_ install Chrome and grab the extension. If it _is_ somehow the hosts file, then I suppose it won't work in Chrome either.

**Comment by anfo55** [comment]
Yes I will load Firefox (zero addons except Hide Doodles) on a laptop I have lying around and let you know

**Comment by grantwinney** [comment]
So there's _finally_ a doodle in my region so I can test things out. They definitely changed the dom of the small logo (on the search results page) pretty significantly, so it wasn't working. I was able to fix that though.

The main (larger) logo seems to still work okay though. I didn't need to touch that.

**Comment by jstrumwasser** [comment]
Good afternoon,  this does not work in my environment either.  I have updated to Chrome 70, so I suspect this is the case

**Comment by grantwinney** [comment]
@anfo55 I think it's because you had `/?gws_rd=ssl` in the URL, which the extension wasn't matching on. Just realized it when Chrome did the same thing to me. I've modified the extension, so if you update and try again it _should_ work now.

@jstrumwasser It might be the same case for you, not sure...

**Comment by grantwinney** [comment]
Let me know if either of you are still having problems after updating.
