### ISSUE TITLE
The doodle somewhat still appears on Google Maps search results.

### ISSUE THREAD

**Issue by mandresybilly** [grantwinney/hide-google-doodles#4]
To begin with, I love the extension. 
Today, I was searching for a random place on Google Search and opened the featured Google Maps location in the search results. To my great surprise, the annoying little doodle still appears on the Google Logo when I opened the Google Maps link. 
Here is the screenshot:
[https://i.imgur.com/tFiINKQ.png](url)

**Comment by grantwinney** [comment]
Thanks. If you right-click on the logo and "inspect" the element, can you copy and paste the html markup here? I guess there's no logo in our area currently so I can't test it. It looks like the name of the element is the same, so it _should_ work...

**Comment by mandresybilly** [comment]
It seems like there is no doodle on Google's homepage today as far as my region is concerned. 
Too bad I can't help. I will disable the extension for a while until a doodle appears again. And on that day I will reactivate the extension, see whether the issue persists and proceed as you instructed above.

**Comment by mandresybilly** [comment]
Hello! Finally there is a doodle today. I tried to reopen the exact page I opened last time. As you can see on my screenshot below, the extension is active but the doodle still appears on the google maps search results.
[https://imgur.com/a/3hFXgqG](https://imgur.com/a/3hFXgqG`)

As you instructed, I right-clicked on the google doodle and here is the code which appeared:

`<img alt="Paul Klee's 139th Birthday" height="44" src="/logos/doodles/2018/paul-klees-139th-birthday-5599847896842240-s.png" title="Paul Klee's 139th Birthday" width="120" border="0" onload="window.lol&amp;&amp;lol()" data-atf="3">`

**Comment by grantwinney** [comment]
If you update it, it'll be hidden now.
