### ISSUE TITLE
Google Maps search box is displaced as it falls downwards

### ISSUE THREAD

**Issue by mandresybilly** [grantwinney/hide-google-doodles#5]
Opening the search results, I found out this. On the [following screenshot picture](https://i.imgur.com/idxouGY.png), I expanded the **Chrome Menu** on the right to show that any other extension is not used.
Here is the link I used as an in the screenshot:
[https://www.google.com/search?num=20&safe=active&q=moscow+airport&npsic=0&rflfq=1&rlha=0&rllag=55691977,37586842,37020&tbm=lcl&ved=2ahUKEwia5c7vqJ7gAhUBI1AKHUFkA0cQtgN6BAgEEAQ&tbs=lrf:!2m1!1e2!2m1!1e16!3sIAE,lf:1,lf_ui:2&rldoc=1](url)

**Comment by grantwinney** [comment]
Could you try it again, after updating the extension?

**Comment by mandresybilly** [comment]
The bug has been fixed. Thanks!
