### ISSUE TITLE
not working on android firefox

### ISSUE THREAD

**Issue by dbphoto** [grantwinney/hide-google-doodles#8]
I've use this on my desktop and it's working fine. I've had it (or something similar) on my phone, and it worked until today. Any thoughts?

**Comment by grantwinney** [comment]
Maybe the version isn't updated, same issue as #11. Problem is, I haven't used Firefox in quite some time, and can't seem to login to the account I uploaded the extension to. None of my regular email accounts are recognized, and there's no support to contact about it, so the extension is kinda stuck. :/

**Comment by dbphoto** [comment]
Thanks. It seems to be working now.
________________________________

**Comment by grantwinney** [comment]
That's good - thanks for letting me know.
