### ISSUE TITLE
Hide doodle from new Chrome tab

### ISSUE THREAD

**Issue by Nodws** [grantwinney/hide-google-doodles#9]
block from
google.com/_/chrome/newtab

supper annoying, tried also the chrome flag but no go

**Comment by grantwinney** [comment]
I've tried before, but it's tougher than modifying the search page. It means creating a whole new page to [replace the new tab page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/chrome_url_overrides), and there's a lot of functionality on that built-in page that this extension shouldn't just toss out.

**Comment by Nodws** [comment]
I found a workaround, if your customize the page with any background the doodle goes away so I just selected a white image from my computer :+1:

**Comment by grantwinney** [comment]
Thanks for the tip! I added a note in the readme.

**Comment by ma11hew28** [comment]
Even if you customize the new tab page, it still shows an animating notification if there's a Google Doodle for the current day. How could I remove (from the new tab page) the HTML element `<button id="logo-doodle-notifier" title="Click to view today’s doodle">` and its contents?

**Comment by grantwinney** [comment]
@ma11hew28 If it's just for you, have you ever tried [stylus](https://chrome.google.com/webstore/detail/stylus-beta/apmmpaebfobifelkijhaljbmpcgbjbdo)? You might be able to target that page (does anything show  up in the address bar when the default new tab is open?) in stylus, and then just use a bit of css, like this:

```css
#logo-doodle-notifier { display: none !important; }
```

**Comment by ma11hew28** [comment]
OK. Thanks, @grantwinney. I haven't tried Stylus, but thanks for the suggestion. Maybe I'll check it out, but I think I'd actually prefer to just replace the New Tab page (as you initially suggested) with a blank page. I've never built a browser extension before, so I'm going to learn how to do that.
